community/urls.py
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from . import views


app_name='community'

urlpatterns = [
    url(r'^register/$', views.RegisterAccountView.as_view(), name='register'),
    url(r'^profile/$', views.profile_edit, name='profile'),
    url(r'^subscriptions/$', views.subscriptions, name='subscriptions'),
    url(r'^organization/edit$', views.participant_edit, name='participant_edit'),
    url(r'^organizations/new$', views.participant_new, name='participant_new'),
    url(r'^organizations/$', login_required(views.ParticipantListView.as_view()), name='participant_list'),
    url(r'^organizations/(?P<pk>\d+)/detail/$', login_required(views.ParticipantDetailView.as_view()), name='participant_detail'),

    # Subscriptions
    url(r'^organizations/(?P<pk>\d+)/detail/toggle-subscription/$', views.participant_toggle_subscription, name='participant_toggle_subscription'),

]

registry/urls.py
from rest_framework import routers
from django.conf.urls import include
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from .views import (index, service, document, end_point, data_standard, data_exchange_format,
                    infrastructure, technical_interface, technical_interface_binding, contact_point)

from .serializers.user import UserViewSet
from .serializers.participant import ParticipantViewSet
from .serializers.participant_category import ParticipantCategoryViewSet
from .serializers.service import ServiceViewSet
from .serializers.version_category import VersionCategoryViewSet
from .serializers.implementation import ImplementationStatusCategoryViewSet
from .serializers.implementation import ImplementationMaturityCategoryViewSet
from .serializers.registration_status_category import RegistrationStatusCategoryViewSet
from .serializers.data_category import DataCategoryViewSet
from .serializers.activity_category import ActivityCategoryViewSet
from .serializers.stakeholder_category import StakeholderCategoryViewSet
from .serializers.region_category import RegionCategoryViewSet
from .serializers.flight_phase_category import FlightPhaseCategoryViewSet
from .serializers.technical_interface import TechnicalInterfaceViewSet
from .serializers.technical_interface_binding import TechnicalInterfaceBindingProfileViewSet
from .serializers.infrastructure import InfrastructureProfileViewSet
from .serializers.data_standard import DataStandardViewSet
# from .serializers.data_exchange_format import DataExchangeFormatServiceViewSet
# from .serializers.end_point import EndPointViewSet


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('participants', ParticipantViewSet)
router.register('participant-categories', ParticipantCategoryViewSet)
router.register('services', ServiceViewSet)
router.register('version-categories', VersionCategoryViewSet)
router.register('implementation-status-categories', ImplementationStatusCategoryViewSet)
router.register('implementation-maturity-categories', ImplementationMaturityCategoryViewSet)
router.register('registration-status-categories', RegistrationStatusCategoryViewSet)
router.register('data-categories', DataCategoryViewSet)
router.register('activity-categories', ActivityCategoryViewSet)
router.register('stakeholder-categories', StakeholderCategoryViewSet)
router.register('region-categories', RegionCategoryViewSet)
router.register('flight-phase-categories', FlightPhaseCategoryViewSet)
router.register('technical-interfaces', TechnicalInterfaceViewSet)
router.register('data-standards', DataStandardViewSet)
router.register('infrastructure-profiles', InfrastructureProfileViewSet)
router.register('profile-technical-interface-bindings', TechnicalInterfaceBindingProfileViewSet)


app_name='registry'

urlpatterns = [
    url(r'^api/', include(router.urls)),
    
    url(r'^login/$', login, {'template_name':'registry/login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, {'login_url':'/login/'}, name='logout'),
    url(r'^registry/$', index.index_view, name='index'),

    # Service
    url(r'^organization/services/list/$', service.organization_service_list, name='participant_service_list'),
    # url(r'^services/$', login_required(service.ServiceListView.as_view()), name='service_list'),
    url(r'^services/$', service.service_list, name='service_list'),
    url(r'^services/new/$', service.service_new, name='service_new'),
    url(r'^services/(?P<pk>\d+)/detail/$', login_required(service.ServiceDetailView.as_view()), name='service_detail'),
    url(r'^services/(?P<pk>\d+)/edit/$', service.service_edit, name='service_edit'),

    # Technical Interface
    url(r'^services/(?P<pk>\d+)/technical-interface/new/$', technical_interface.technical_interface_new, name='technical_interface_new'),
    url(r'^services/(?P<pk>\d+)/technical-interface/edit/$', technical_interface.technical_interface_edit, name='technical_interface_edit'),
    url(r'^services/(?P<pk>\d+)/technical-interface/detail/$', login_required(technical_interface.TechnicalInterfaceDetailView.as_view()), name='technical_interface_detail'),

    # Infrastructure Description
    url(r'^infrastructure-description/(?P<pk>\d+)/detail/$', login_required(infrastructure.InfrastructureDescriptionDetailView.as_view()), name='infrastructure_description_detail'),
    url(r'^technical-interface/(?P<pk>\d+)/infrastructure-description/new/$', infrastructure.infrastructure_description_new, name='infrastructure_description_new'),
    url(r'^technical-interface/(?P<pk>\d+)/infrastructure-description/edit/$', infrastructure.infrastructure_description_edit, name='infrastructure_description_edit'),

    # Documents
    url(r'^reference-documents/$', document.reference_document_list, name='reference_document_list'),
    url(r'^service-documents/(?P<pk>\d+)/detail/$', login_required(document.ServiceDocumentDetailView.as_view()), name='service_document_detail'),
    url(r'^participant-documents/(?P<pk>\d+)/detail/$', login_required(document.ParticipantDocumentDetailView.as_view()), name='participant_document_detail'),
    url(r'^infrastructure-reference-documents/(?P<pk>\d+)/detail/$', login_required(document.InfrastructureReferenceDocumentDetailView.as_view()), name='infrastructure_reference_document_detail'),
    url(r'^infrastructure-description-documents/(?P<pk>\d+)/detail/$', login_required(document.InfrastructureDescriptionDocumentDetailView.as_view()), name='infrastructure_description_document_detail'),
    url(r'^service-data-exchange-format-documents/(?P<pk>\d+)/detail/$', login_required(document.DataExchangeFormatServiceDocumentDetailView.as_view()), name='data_exchange_format_service_document_detail'),
    url(r'^technical-interface-documents/(?P<pk>\d+)/detail/$', login_required(document.TechnicalInterfaceDocumentDetailView.as_view()), name='technical_interface_document_detail'),

    # Contact Points
    url(r'^service-contact-points/(?P<pk>\d+)/detail/$', login_required(contact_point.ServiceContactPointDetailView.as_view()), name='service_contact_point_detail'),
    url(r'^participant-contact-points/(?P<pk>\d+)/detail/$', login_required(contact_point.ParticipantContactPointDetailView.as_view()), name='participant_contact_point_detail'),

    # End Points
    url(r'^technical-interface/(?P<pk>\d+)/end-points/edit/$', end_point.end_points_edit, name='end_points_edit'),
    url(r'^end-points/(?P<pk>\d+)/detail/$', login_required(end_point.EndPointDetailView.as_view()), name='end_point_detail'),

    # Data Standards
    url(r'^data-standards/(?P<pk>\d+)/detail/$', login_required(data_standard.DataStandardDetailView.as_view()), name='data_standard_detail'),

    # Data Exchange Formats
    url(r'^technical-interface/(?P<pk>\d+)/data-exchange-formats/edit/$', data_exchange_format.data_exchange_formats_edit, name='data_exchange_formats_edit'),
    url(r'^service-data-exchange-formats/(?P<pk>\d+)/detail/$', login_required(data_exchange_format.DataExchangeFormatServiceDetailView.as_view()), name='service_data_exchange_format_detail'),

    # Infrastructure Profile
    url(r'^infrastructure-profile/(?P<pk>\d+)/detail/$', login_required(infrastructure.InfrastructureProfileDetailView.as_view()), name='infrastructure_profile_detail'),

    # Technical Interface Binding
    url(r'^infrastructure-profile/technical-interface-binding/(?P<pk>\d+)/detail/$', login_required(technical_interface_binding.TechnicalInterfaceBindingProfileDetailView.as_view()), name='profile_technical_interface_binding_detail'),
    url(r'^infrastructure-description/technical-interface-binding/(?P<pk>\d+)/detail/$', login_required(technical_interface_binding.TechnicalInterfaceBindingDescriptionDetailView.as_view()), name='description_technical_interface_binding_detail'),

    # Subscriptions
    url(r'^services/(?P<pk>\d+)/detail/toggle-subscription/$', service.service_toggle_subscription, name='service_toggle_subscription'),


    # url(r'^about/$', views.about, name='about'),
]

# ReferenceDocumentDetailView
# DataExchangeFormatApplicationDocumentDetailView
# ApplicationDocumentDetailView
# ParticipantDocumentDetailView

swim_registry/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
#from .admin import admin_site
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from .settings.base import MEDIA_ROOT, MEDIA_URL


urlpatterns = i18n_patterns(
    # url(r'^admin/', include(admin_site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^', include('website.urls')),
    url(r'^', include('community.urls')),
    url(r'^', include('registry.urls')),
)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

admin.site.site_header = _('SWIM Registry Administration')

website/urls.py
from django.conf.urls import url
from . import views

app_name='website'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

community/models/participant.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from swim_registry.models import TimeStampedModel


class Participant(TimeStampedModel):
    name = models.CharField(max_length=255, verbose_name=_('name'))
    description = models.TextField(blank=True, verbose_name=_('description'))
    website = models.URLField(blank=True, verbose_name=_('website'))
    category = models.ForeignKey('community.ParticipantCategory', related_name='participants', verbose_name=_('participant category'))
    image = models.ImageField(upload_to = 'participants/profiles/images/', default = 'participants/profiles/images/none/default.svg', verbose_name=_('image'))
    reviewed = models.BooleanField(default=True, verbose_name=_('reviewed'))

    # documents = models.ManyToManyField(ParticipantDocument, related_name='participants')
    # contact_points = models.ManyToManyField(ContactPoint, related_name='participants')

    class Meta:
        verbose_name=_('participant')

    def save(self, *args, **kwargs):
        # all services are safe if organization is safe
        super().save(*args, **kwargs)
        if self.reviewed:
            for service in self.services.all():
                service.reviewed = True
                service.save()

    def __str__(self):
        return self.name

community/models/participant_category.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ParticipantCategory(models.Model):
    AIRSPACE_COMPANY = 'AIRSPACE COMPANY'
    RESEARCH_ORGANIZATION = 'RESEARCH ORGANIZATION'
    AIRPORT = 'AIRPORT'
    AERODROME = 'AERODROME'
    RESEARCH_INSTITUTION = 'RESEARCH INSTITUTION'
    PUBLIC_AGENCY = 'PUBLIC AGENCY'
    OTHER = 'OTHER'

    CHOICES = (
        (AIRSPACE_COMPANY, _('Airspace company')),
        (RESEARCH_ORGANIZATION, _('Research Organization')),
        (AIRPORT, _('Airport')),
        (AERODROME, _('Aerodrome')),
        (RESEARCH_INSTITUTION, _('Research Institution')),
        (PUBLIC_AGENCY, _( 'Public Agency')),
        (OTHER, _('Other')),
    )

    name = models.CharField(max_length=50, choices=CHOICES, unique=True, verbose_name=_('name'))

    class Meta:
        verbose_name = _('participant category')
        verbose_name_plural = _('participant categories')

    def __str__(self):
        return self.name

community/models/registration_request.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from swim_registry.models import TimeStampedModel
from .profile import Profile
from community.utils import send_confirmartion_mail


class RegistrationRequest(TimeStampedModel):
    first_name = models.CharField(max_length=255, verbose_name=_('first name'))
    last_name = models.CharField(max_length=255, verbose_name=_('last name'))
    email = models.EmailField(verbose_name=_('email'))
    organization = models.CharField(max_length=255, verbose_name=_('organization'))
    role = models.CharField(max_length=255, verbose_name=_('institutional role'))
    note = models.TextField(verbose_name=_('note'))

    def register(self):
        password = User.objects.make_random_password()
        user = User.objects.create_user(
                        username=self.email,
                        email=self.email,
                        password=password,
                        first_name=self.first_name,
                        last_name=self.last_name
                    )
        profile = Profile(
                            user=user,
                            # TODO
                        )
        profile.save()
        send_confirmartion_mail(profile.full_name, self.email, password)
        
    class Meta:
        verbose_name=_('registration request')

    def __str__(self):
        return '{self.last_name}, {self.first_name}'.format(self=self)

community/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from .models.profile import Profile
from .models.participant import Participant
from .models.registration_request import RegistrationRequest


class RegistrationRequestForm(forms.ModelForm):
    approved = forms.TypedChoiceField(required=False, coerce=lambda x: x =='True',
                                   choices=((False, _('No')), (True, _('Yes'))), label=_('approved'))

    class Meta:
        model = RegistrationRequest
        fields = '__all__'
        widgets = {
            'first_name': widgets.TextInput(attrs={'id': 'first_name_id', 'class': 'form-control', 'autofocus': True, 'placeholder': _('First Name')}),
            'last_name': widgets.TextInput(attrs={'id': 'last_name_id', 'class': 'form-control', 'placeholder': _('Last Name')}),
            'email': widgets.TextInput(attrs={'id': 'email_id', 'class': 'form-control', 'placeholder': _('E-mail')}),
            'organization': widgets.TextInput(attrs={'id': 'organization_id', 'class': 'form-control', 'placeholder': _('Organization')}),
            'role': widgets.TextInput(attrs={'id': 'role_id', 'class': 'form-control', 'placeholder': _('Institutional Role')}),
            'note': widgets.Textarea(attrs={'id': 'note_id', 'class': 'form-control', 'placeholder': _('Describe how you intend to use the SWIM Registry.')}),
            'approved': widgets.Select(),
         }

    def save(self, commit=True):
        request = super().save(commit=commit)
        approved = self.cleaned_data.get('approved', None)
        if approved:
            request.register()
        return request

    def is_valid(self):
        if not super().is_valid():
            return False
        user_exists = User.objects.filter(username=self.cleaned_data['email']).exists()
        if user_exists:
            self.add_error('email', ValidationError(_('Email already registered'), code='invalid_email'))
            return False
        return True


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=255, required=True, label=_('first name'))
    last_name = forms.CharField(max_length=255, required=True, label=_('last name'))
    email = forms.EmailField(max_length=255, required=True, label=_('email'))

    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'notification_frequency']
        widgets = {
            'notification_frequency': widgets.Select(attrs={'id': 'notification_frequency_id', 'class': 'form-control'}),
        }


class ParticipantForm(forms.ModelForm):

    class Meta:
        model = Participant
        exclude = ['reviewed', 'contact_points', 'documents']
        widgets = {
            'name': widgets.TextInput(attrs={'id': 'name_id', 'class': 'form-control', 'placeholder': _('Name')}),
            'description': widgets.Textarea(attrs={'id': 'description_id', 'class': 'form-control', 'placeholder': _('Description')}),
            'category': widgets.Select(attrs={'id': 'category_id', 'class': 'form-control'}),
        }

community/templates/community/organization_detail.html
{% extends 'registry/base.html' %}

{% block container %}
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">

           <div class="page-header">
                <h1>{{ organization.name }}</h1>
            </div>

          <div class="row">
            <div class="col-md-3">
              <img src="{{organization.image.url}}" width="150" alt="organization logo">
            </div>
            <div class="col-md-9">
              <p>
                <b>Category: </b>
                {{organization.category}}
              </p>
              <p>
                {{organization.description}}
              </p>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Services</h3>
                </div>
                <!-- <div class="panel-body"></div> <ul class="information-panel"></ul>-->
                <div class="list-group">
                  {% for service in organization.services.all %}
                      <li class="list-group-item">
                        <a href="{% url 'registry:service_detail' pk=service.pk %}">
                          <img src="{{ service.image.url }}" alt="logo">
                          {{ service.name }}: {{ service.description }}
                        </a>
                      </li>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Applications</h3>
                </div>
                <div class="list-group">
                  {% for application in organization.applications.all %}
                      <li class="list-group-item">
                        <img src="{ {application.image.url }}" alt="logo">
                      </li>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Documentation</h3>
                </div>
                <div class="list-group">
                  {% for document in organization.documents.all %}
                      <li class="list-group-item">
                        <img src="{{document.image.url}}" alt="logo">
                      </li>
                  {% endfor %}
                </div>
              </div>

            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Contact Points</h3>
                </div>
                <div class="list-group">
                  {% for contact_point in organization.contact_points.all %}
                      <li class="list-group-item">
                        <img src="{{contact_point.image.url}}" alt="logo">
                      </li>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

{% endblock %}

community/templates/community/organization_list.html
{% extends 'registry/base.html' %}

{% block container %}
    <div class="container">
      <div class="row">

        <div class="col-lg-12">
            <h1 class="page-header">Organizations</h1>
        </div>

        {% for organization in organizations %}
          <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
              <a  href="{% url 'community:organization_detail' organization.pk %}">
                <img class="img-responsive" src="{{organization.image.url}}" width="150" alt="">
              </a>
              <div class="caption">
                <h3>{{organization.name}}</h3>
                <p>{{organization.description|truncatechars:144}}</p>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>

{% endblock %}

community/templates/community/participant_detail.html
{% extends 'registry/base.html' %}
{% load i18n %}

{% block container %}
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">

           <div class="page-header">
                <h1>{{ participant.name }}</h1>
            </div>

          <div class="row">
            <div class="col-md-3">
              <div>
                <img src="{{participant.image.url}}" width="150" alt="participant logo">
              </div>
              {% if subscribed %}
                <button type="button" class="btn btn-default btn-lg toggleSubscription">
                  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                  {% trans "Subscribe" %}
                </button>
              {% else %}
                <button type="button" class="btn btn-default btn-lg toggleSubscription">
                  <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                  {% trans "Subscribe" %}
                </button>
              {% endif %}
            </div>
            <div class="col-md-9">
              <p>
                <b>{% trans "Category" %}: </b>
                {{ participant.category.get_name_display }}
              </p>
              <p>
                {{ participant.description }}
              </p>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">{% trans "Services" %}</h3>
                </div>
                <!-- <div class="panel-body"></div> <ul class="information-panel"></ul>-->
                <div class="list-group">
                  {% for service in participant.services.all %}
                      {% if service.reviewed %}
                        <li class="list-group-item">
                          <p>
                            <img src="{{ service.image.url }}" alt="logo">
                            <a href="{% url 'registry:service_detail' pk=service.pk %}">
                              {{ service.name }}
                            </a>
                            {{ service.description|truncatechars:90 }}
                          </p>
                        </li>
                      {% endif %}
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>

          {% comment %}
          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">{% trans "Applications" %}</h3>
                </div>
                <div class="list-group">
                  {% for application in participant.applications.all %}
                      <li class="list-group-item">
                        <img src="{ {application.image.url }}" alt="logo">
                      </li>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
          {% endcomment %}

          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">{% trans "Documentation" %}</h3>
                </div>
                <div class="list-group">
                  {% for document in participant.documents.all %}
                      <li class="list-group-item">
                        <img src="{{ document.image.url }}" alt="logo">
                        <a href="{% url 'registry:participant_document_detail' pk=document.pk %}"> {{ document.name }}</a>
                      </li>
                  {% endfor %}
                </div>
              </div>

            </div>
          </div>

          <div class="row">
            <div class="col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">{% trans "Contact Points" %}</h3>
                </div>
                <div class="list-group">
                  {% for contact_point in participant.contact_points.all %}
                      <li class="list-group-item">
                        <img src="{{contact_point.image.url}}" alt="logo">
                        <a href="{% url 'registry:participant_contact_point_detail' pk=contact_point.pk %}">{{ contact_point.name }}</a>
                      </li>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

{% endblock %}

community/templates/community/profile.html
{% extends 'registry/base.html' %}
{% load i18n %}

{% block container %}
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">

           <h1>{% trans "Profile settings" %}</h1>


          {% if messages %}
              <div class="alert alert-success">
                <button type="button" class="close" data-dismiss='alert' aria-hidden='true'>
                        &times;
                </button>
                {% for message in messages %}
                  <li>{{ message }}</li>
                {% endfor %}
              </div>
          {% endif %}

          {% if form.errors %}
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss='alert' aria-hidden='true'>
                      &times;
              </button>
              {% for field in form %}
                {% if field.errors %}
                <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                {% endif %}
              {% endfor %}
            </div>
          {% endif %}

          <form method="POST" class="post-form">
            {% csrf_token %}

            <div class="page-header">
              <h2>{{ user.first_name }} {{ user.last_name }}</h2>
            </div>

            {% if not form.instance.organization.pk %}
              <div class="row">
                <a class="btn btn-primary pull-right" role="button" href="{% url 'community:participant_new' %}" role="button">{% trans "Create your organization" %} <span aria-hidden="true">&raquo;</span></a>
              </div>
            {% endif %}
  
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="first_name_id">{% trans "First name" %}</label>
                  <input type="text" name="first_name" class="form-control" id="first_name_id" value="{{ user.first_name }}">
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="last_name_id">{% trans "Last name" %}</label>
                  <input type="text" name="last_name" class="form-control" id="last_name_id" value="{{ user.last_name }}">
                </div>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="email_id">{{ form.email.label }}</label>
                  <input type="text" name="email" class="form-control" id="email_id" value="{{user.email}}" readonly>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="notification_frequency_id">{{ form.notification_frequency.label }}</label>
                  {{ form.notification_frequency }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">{% trans "Following Organizations" %}</h3>
                  </div>
                  <!-- <div class="panel-body"></div> <ul class="information-panel"></ul>-->
                  <div class="list-group">
                    {% for organization in form.instance.following_organizations.all %}
                      <li class="list-group-item">
                        <p>
                          <img src="{{ organization.image.url }}" alt="logo">
                          <a href="{% url 'community:participant_detail' pk=organization.pk %}">
                            {{ organization.name }}
                          </a>
                          {{ organization.description|truncatechars:90 }}
                        </p>
                      </li>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-md-12">
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h3 class="panel-title">{% trans "Following Services" %}</h3>
                  </div>
                  <!-- <div class="panel-body"></div> <ul class="information-panel"></ul>-->
                  <div class="list-group">
                    {% for service in form.instance.following_services.all %}
                        <li class="list-group-item">
                          <p>
                            <img src="{{ service.image.url }}" alt="logo">
                            <a href="{% url 'registry:service_detail' pk=service.pk %}">
                              {{ service.name }}
                            </a>
                            {{ service.description|truncatechars:90 }}
                          </p>
                        </li>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>

            <button class="btn btn-primary pull-right" name="submit" type="submit">{% trans "Save" %}</button>
          </form>
        </div>
      </div>
    </div>

{% endblock %}