community/urls.py
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from . import views


app_name='community'

urlpatterns = [
    url(r'^register/$', views.RegisterAccountView.as_view(), name='register'),
    url(r'^profile/$', views.profile_edit, name='profile'),
    url(r'^subscriptions/$', views.subscriptions, name='subscriptions'),
    url(r'^organization/edit$', views.participant_edit, name='participant_edit'),
    url(r'^organizations/new$', views.participant_new, name='participant_new'),
    url(r'^organizations/$', login_required(views.ParticipantListView.as_view()), name='participant_list'),
    url(r'^organizations/(?P<pk>\d+)/detail/$', login_required(views.ParticipantDetailView.as_view()), name='participant_detail'),

    # Subscriptions
    url(r'^organizations/(?P<pk>\d+)/detail/toggle-subscription/$', views.participant_toggle_subscription, name='participant_toggle_subscription'),

]

registry/urls.py
from rest_framework import routers
from django.conf.urls import include
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from .views import (index, service, document, end_point, data_standard, data_exchange_format,
                    infrastructure, technical_interface, technical_interface_binding, contact_point)

from .serializers.user import UserViewSet
from .serializers.participant import ParticipantViewSet
from .serializers.participant_category import ParticipantCategoryViewSet
from .serializers.service import ServiceViewSet
from .serializers.version_category import VersionCategoryViewSet
from .serializers.implementation import ImplementationStatusCategoryViewSet
from .serializers.implementation import ImplementationMaturityCategoryViewSet
from .serializers.registration_status_category import RegistrationStatusCategoryViewSet
from .serializers.data_category import DataCategoryViewSet
from .serializers.activity_category import ActivityCategoryViewSet
from .serializers.stakeholder_category import StakeholderCategoryViewSet
from .serializers.region_category import RegionCategoryViewSet
from .serializers.flight_phase_category import FlightPhaseCategoryViewSet
from .serializers.technical_interface import TechnicalInterfaceViewSet
from .serializers.technical_interface_binding import TechnicalInterfaceBindingProfileViewSet
from .serializers.infrastructure import InfrastructureProfileViewSet
from .serializers.data_standard import DataStandardViewSet
# from .serializers.data_exchange_format import DataExchangeFormatServiceViewSet
# from .serializers.end_point import EndPointViewSet


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('participants', ParticipantViewSet)
router.register('participant-categories', ParticipantCategoryViewSet)
router.register('services', ServiceViewSet)
router.register('version-categories', VersionCategoryViewSet)
router.register('implementation-status-categories', ImplementationStatusCategoryViewSet)
router.register('implementation-maturity-categories', ImplementationMaturityCategoryViewSet)
router.register('registration-status-categories', RegistrationStatusCategoryViewSet)
router.register('data-categories', DataCategoryViewSet)
router.register('activity-categories', ActivityCategoryViewSet)
router.register('stakeholder-categories', StakeholderCategoryViewSet)
router.register('region-categories', RegionCategoryViewSet)
router.register('flight-phase-categories', FlightPhaseCategoryViewSet)
router.register('technical-interfaces', TechnicalInterfaceViewSet)
router.register('data-standards', DataStandardViewSet)
router.register('infrastructure-profiles', InfrastructureProfileViewSet)
router.register('profile-technical-interface-bindings', TechnicalInterfaceBindingProfileViewSet)


app_name='registry'

urlpatterns = [
    url(r'^api/', include(router.urls)),
    
    url(r'^login/$', login, {'template_name':'registry/login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, {'login_url':'/login/'}, name='logout'),
    url(r'^registry/$', index.index_view, name='index'),

    # Service
    url(r'^organization/services/list/$', service.organization_service_list, name='participant_service_list'),
    # url(r'^services/$', login_required(service.ServiceListView.as_view()), name='service_list'),
    url(r'^services/$', service.service_list, name='service_list'),
    url(r'^services/new/$', service.service_new, name='service_new'),
    url(r'^services/(?P<pk>\d+)/detail/$', login_required(service.ServiceDetailView.as_view()), name='service_detail'),
    url(r'^services/(?P<pk>\d+)/edit/$', service.service_edit, name='service_edit'),

    # Technical Interface
    url(r'^services/(?P<pk>\d+)/technical-interface/new/$', technical_interface.technical_interface_new, name='technical_interface_new'),
    url(r'^services/(?P<pk>\d+)/technical-interface/edit/$', technical_interface.technical_interface_edit, name='technical_interface_edit'),
    url(r'^services/(?P<pk>\d+)/technical-interface/detail/$', login_required(technical_interface.TechnicalInterfaceDetailView.as_view()), name='technical_interface_detail'),

    # Infrastructure Description
    url(r'^infrastructure-description/(?P<pk>\d+)/detail/$', login_required(infrastructure.InfrastructureDescriptionDetailView.as_view()), name='infrastructure_description_detail'),
    url(r'^technical-interface/(?P<pk>\d+)/infrastructure-description/new/$', infrastructure.infrastructure_description_new, name='infrastructure_description_new'),
    url(r'^technical-interface/(?P<pk>\d+)/infrastructure-description/edit/$', infrastructure.infrastructure_description_edit, name='infrastructure_description_edit'),

    # Documents
    url(r'^reference-documents/$', document.reference_document_list, name='reference_document_list'),
    url(r'^service-documents/(?P<pk>\d+)/detail/$', login_required(document.ServiceDocumentDetailView.as_view()), name='service_document_detail'),
    url(r'^participant-documents/(?P<pk>\d+)/detail/$', login_required(document.ParticipantDocumentDetailView.as_view()), name='participant_document_detail'),
    url(r'^infrastructure-reference-documents/(?P<pk>\d+)/detail/$', login_required(document.InfrastructureReferenceDocumentDetailView.as_view()), name='infrastructure_reference_document_detail'),
    url(r'^infrastructure-description-documents/(?P<pk>\d+)/detail/$', login_required(document.InfrastructureDescriptionDocumentDetailView.as_view()), name='infrastructure_description_document_detail'),
    url(r'^service-data-exchange-format-documents/(?P<pk>\d+)/detail/$', login_required(document.DataExchangeFormatServiceDocumentDetailView.as_view()), name='data_exchange_format_service_document_detail'),
    url(r'^technical-interface-documents/(?P<pk>\d+)/detail/$', login_required(document.TechnicalInterfaceDocumentDetailView.as_view()), name='technical_interface_document_detail'),

    # Contact Points
    url(r'^service-contact-points/(?P<pk>\d+)/detail/$', login_required(contact_point.ServiceContactPointDetailView.as_view()), name='service_contact_point_detail'),
    url(r'^participant-contact-points/(?P<pk>\d+)/detail/$', login_required(contact_point.ParticipantContactPointDetailView.as_view()), name='participant_contact_point_detail'),

    # End Points
    url(r'^technical-interface/(?P<pk>\d+)/end-points/edit/$', end_point.end_points_edit, name='end_points_edit'),
    url(r'^end-points/(?P<pk>\d+)/detail/$', login_required(end_point.EndPointDetailView.as_view()), name='end_point_detail'),

    # Data Standards
    url(r'^data-standards/(?P<pk>\d+)/detail/$', login_required(data_standard.DataStandardDetailView.as_view()), name='data_standard_detail'),

    # Data Exchange Formats
    url(r'^technical-interface/(?P<pk>\d+)/data-exchange-formats/edit/$', data_exchange_format.data_exchange_formats_edit, name='data_exchange_formats_edit'),
    url(r'^service-data-exchange-formats/(?P<pk>\d+)/detail/$', login_required(data_exchange_format.DataExchangeFormatServiceDetailView.as_view()), name='service_data_exchange_format_detail'),

    # Infrastructure Profile
    url(r'^infrastructure-profile/(?P<pk>\d+)/detail/$', login_required(infrastructure.InfrastructureProfileDetailView.as_view()), name='infrastructure_profile_detail'),

    # Technical Interface Binding
    url(r'^infrastructure-profile/technical-interface-binding/(?P<pk>\d+)/detail/$', login_required(technical_interface_binding.TechnicalInterfaceBindingProfileDetailView.as_view()), name='profile_technical_interface_binding_detail'),
    url(r'^infrastructure-description/technical-interface-binding/(?P<pk>\d+)/detail/$', login_required(technical_interface_binding.TechnicalInterfaceBindingDescriptionDetailView.as_view()), name='description_technical_interface_binding_detail'),

    # Subscriptions
    url(r'^services/(?P<pk>\d+)/detail/toggle-subscription/$', service.service_toggle_subscription, name='service_toggle_subscription'),


    # url(r'^about/$', views.about, name='about'),
]

# ReferenceDocumentDetailView
# DataExchangeFormatApplicationDocumentDetailView
# ApplicationDocumentDetailView
# ParticipantDocumentDetailView

swim_registry/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
#from .admin import admin_site
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from .settings.base import MEDIA_ROOT, MEDIA_URL


urlpatterns = i18n_patterns(
    # url(r'^admin/', include(admin_site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^', include('website.urls')),
    url(r'^', include('community.urls')),
    url(r'^', include('registry.urls')),
)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

admin.site.site_header = _('SWIM Registry Administration')

website/urls.py
from django.conf.urls import url
from . import views

app_name='website'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

registry/models/activity_category.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class ActivityCategory(models.Model):
    AERONAUTICAL_INFORMATION_MANAGEMENT = 'AERONAUTICAL INFORMATION MANAGEMENT'
    AIRPORT_CDM = 'AIRPORT CDM'
    COLLISION_AVOIDANCE = 'COLLISION AVOIDANCE'
    SURVEILLANCE_INFRASTRUCTURE = 'SURVEILLANCE INFRASTRUCTURE'
    TRAFFIC_SEQUENCING = 'TRAFFIC SEQUENCING'
    TRAFFIC_SYNCHRONISATION = 'TRAFFIC SYNCHRONISATION'
    TRAJECTORY_EXECUTION_AND_CONFORMANCE_MONITORING = 'TRAJECTORY EXECUTION AND CONFORMANCE MONITORING'
    CNS_INFRASTRUCTURE = 'CNS INFRASTRUCTURE'
    FLIGHT_INFORMATION_MANAGEMENT = 'FLIGHT INFORMATION MANAGEMENT'
    NAVIGTION_INFRASTRUCTURE = 'NAVIGTION INFRASTRUCTURE'
    ROUTE_DESIGN = 'ROUTE DESIGN'
    SEPARATION_PROVISION = 'SEPARATION PROVISION'
    TRAJECTORY_PLANNING = 'TRAJECTORY PLANNING'
    AIRSPACE_AND_SURFACE_STRUCTURE_DESIGN = 'AIRSPACE AND SURFACE STRUCTURE DESIGN'
    ATM_INFORMATION_MANAGEMENT = 'ATM INFORMATION MANAGEMENT'
    COMMUNICATION_INFRASTRUCTURE = 'COMMUNICATION INFRASTRUCTURE'
    METEOROLOGICAL_INFORMATION = 'METEOROLOGICAL INFORMATION'
    ROUTE_ASSIGNMENT_AND_GUIDANCE = 'ROUTE ASSIGNMENT AND GUIDANCE'
    AIRSPACE_AND_SURFACE_STRUCTURE_ALLOCATION = 'AIRSPACE AND SURFACE STRUCTURE ALLOCATION'
    MET_INFORMATION_MANAGEMENT = 'MET INFORMATION MANAGEMENT'
    AIRSPACE_ACCESS = 'AIRSPACE ACCESS'
    SHARED_INFORMATION_SERVICE_MANAGEMENT  = 'SHARED INFORMATION SERVICE MANAGEMENT'
    DEMAND_AND_CAPACITY_BALANCING = 'DEMAND AND CAPACITY BALANCING'
    CONFLICT_MANAGEMENT = 'CONFLICT MANAGEMENT'
    AIRPORT_MANAGEMENT = 'AIRPORT MANAGEMENT'
    TRAJECTORY_MANAGEMENT = 'TRAJECTORY MANAGEMENT'
    ATM_NETWORK_MANAGEMENT = 'ATM NETWORK MANAGEMENT'

    CHOICES = (
        (AERONAUTICAL_INFORMATION_MANAGEMENT, _('Aeronautical Information Management')),
        (AIRPORT_CDM, _('Airport CDM')),
        (COLLISION_AVOIDANCE, _('Collision Avoidance')),
        (SURVEILLANCE_INFRASTRUCTURE, _('Surveillance Infrastructure')),
        (TRAFFIC_SEQUENCING, _('Traffic Sequencing')),
        (TRAFFIC_SYNCHRONISATION, _('Traffic Synchronisation')),
        (TRAJECTORY_EXECUTION_AND_CONFORMANCE_MONITORING, _('Trajectory Execution And Conformance Monitoring')),
        (CNS_INFRASTRUCTURE, _('CNS Infrastructure')),
        (FLIGHT_INFORMATION_MANAGEMENT, _('Flight Information Management')),
        (NAVIGTION_INFRASTRUCTURE, _('Navigtion Infrastructure')),
        (ROUTE_DESIGN, _('Route Design')),
        (SEPARATION_PROVISION, _('Separation Provision')),
        (TRAJECTORY_PLANNING, _('Trajectory Planning')),
        (AIRSPACE_AND_SURFACE_STRUCTURE_DESIGN, _('Airspace And Surface Structure Design')),
        (ATM_INFORMATION_MANAGEMENT, _('ATM Information Management')),
        (COMMUNICATION_INFRASTRUCTURE, _('Communication Infrastructure')),
        (METEOROLOGICAL_INFORMATION, _('Meteorological Information')),
        (ROUTE_ASSIGNMENT_AND_GUIDANCE, _('Route Assignment And Guidance')),
        (AIRSPACE_AND_SURFACE_STRUCTURE_ALLOCATION, _('Airspace And Surface Structure Allocation')),
        (MET_INFORMATION_MANAGEMENT, _('MET Information Management')),
        (AIRSPACE_ACCESS, _('Airspace Access')),
        (SHARED_INFORMATION_SERVICE_MANAGEMENT , _('Shared Information Service Management')),
        (DEMAND_AND_CAPACITY_BALANCING, _('Demand And Capacity Balancing')),
        (CONFLICT_MANAGEMENT, _('Conflict Management')),
        (AIRPORT_MANAGEMENT, _('Airport Management')),
        (TRAJECTORY_MANAGEMENT, _('Trajectory Management')),
        (ATM_NETWORK_MANAGEMENT, _('ATM Network Management')),
    )

    name = models.CharField(max_length=50, choices=CHOICES, unique=True, verbose_name=_('name'))

    class Meta:
        verbose_name = _('ATM activity category')
        verbose_name_plural = _('ATM activity categories')


    def __str__(self):
        return self.name

registry/models/application.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from swim_registry.models import TimeStampedModel, DocumentModel


class Application(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True, verbose_name=_('name'))
    organization = models.ForeignKey('community.Participant', related_name='applications', verbose_name=_('organization')) # avoid circular imports
    version = models.CharField(max_length=50, verbose_name=_('version'))
    image = models.ImageField(upload_to = 'applications/profiles/images/', default = 'applications/profiles/images/none/default.jpg', verbose_name=_('image'))
    opensource = models.BooleanField(default=False, verbose_name=_('open source'))
    payable = models.BooleanField(default=False, verbose_name=_('payable'))

    version_category = models.ForeignKey('registry.VersionCategory', related_name='applications', verbose_name=_('version category'))
    implementation_status = models.ForeignKey('registry.ImplementationStatusCategory', related_name='applications', verbose_name=_('implementation status'))
    implementation_maturity = models.ForeignKey('registry.ImplementationMaturityCategory', related_name='applications', verbose_name=_('implementation maurity'))
    registration_status = models.ForeignKey('registry.RegistrationStatusCategory', related_name='applications', verbose_name=_('registration status'))

    data_categories = models.ManyToManyField('registry.DataCategory', related_name='applications', verbose_name=_('ATM data categories'))
    activity_categories = models.ManyToManyField('registry.ActivityCategory', related_name='applications', verbose_name=_('ATM activity categories'))
    stakeholders = models.ManyToManyField('registry.StakeholderCategory', related_name='applications', verbose_name=_('stakeholders'))
    regions = models.ManyToManyField('registry.RegionCategory', related_name='applications', verbose_name=_('regions'))
    flight_phases = models.ManyToManyField('registry.FlightPhaseCategory', related_name='applications', verbose_name=_('flight phases'))

    data_standards = models.ManyToManyField('registry.DataStandard', related_name='applications', verbose_name=_('data standards'))
    consumed_services = models.ManyToManyField('registry.Service', related_name='applications', verbose_name=_('consumed services'))

    reviewed = models.BooleanField(default=False, verbose_name=_('reviewed'))
    # workflow = models.OneToOneField('registry.Workflow', related_name='application', verbose_name=_('workflow'))


    # files = models.ManyToManyField(ApplicationFile, related_name='applications')

    # data_exchange_formats = models.ManyToManyField(DataExchangeFormat, related_name='applications')
    # documents = models.ManyToManyField(ApplicationDocument, related_name='applications')
    # contact_points = models.ManyToManyField(ContactPoint, related_name='applications')

    ## events = models.ManyToManyField(Event, related_name='applications')
    ##  quality_service_conditions = models.OneToOneField(QualityOfServiceCondition, related_name='applications')


    @property
    def organization_name(self):
        return self.organization.name

    def __str__(self):
        return self.name


class ApplicationFile(DocumentModel):
    file = models.FileField(upload_to = 'applications/files/', null=False)
    image = models.ImageField(upload_to = 'applications/files/images/', default = 'applications/files/images/none/default.jpg', null=True)
    application = models.ForeignKey(Application, related_name='files')

registry/templates/registry/base.html
{% extends "registry/base_login.html" %}
{% load i18n %}
{% load staticfiles %}

{% block body %}
    <!-- Static navbar -->
    <nav class="affix navbar navbar-default navbar-fixed-top navbar-registry">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">{% trans "Toggle navigation" %}</span> {% trans "Menu" %} <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="{% url 'website:index' %}">{% trans "SWIM Registry Brazil" %}</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'registry:index' %}">{% trans "About" %}</a></li>
                    <li><a href="{% url 'community:participant_list' %}">{% trans "Organizations" %}</a></li>
                    <li><a href="{% url 'registry:service_list' %}">{% trans "Services" %}</a></li>
                    {% comment %}
                      <li><a href="#">{% trans "Applications" %}</a></li>
                    {% endcomment %}
                    <li><a href="{% url 'registry:reference_document_list' %}">{% trans "Reference Documents" %}</a></li>
                    <li><a href="#">{% trans "Support" %}</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.first_name }} <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <li class="dropdown-header">{% trans "Settings" %}</li>
                      <li><a href="{% url 'community:profile' %}">{% trans "Profile" %}</a></li>
                      <li><a href="{% url 'community:subscriptions' %}">{% trans "Subscriptions" %}</a></li>
                      
                      {% if user.profile.organization.pk %}
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'community:participant_edit' %}">{% trans "Organization" %}</a></li>
                        <li><a href="{% url 'registry:participant_service_list' %}">{% trans "Services" %}</a></li>
                      {% endif %}

                      <li role="separator" class="divider"></li>
                      <li><a href="{% url 'registry:logout' %}">{% trans "Log out" %}</a></li>
                    </ul>
                  </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <div id="content">
        {% block container %}

        {% endblock %}
    </div>

{% endblock %}

registry/templates/registry/technical_interface_detail.html
{% extends 'registry/base.html' %}
{% load i18n %}

{% block container %}
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">

           <div class="page-header">
                <h1>{% trans "Technical Interface" %}: {{ service.name }} </h1>
            </div>

          <div class="row">
            <div class="col-md-3">
              <img src="{{ service.technical_interface.image.url }}" width="150" alt="service.technical_interface logo">
            </div>
            <div class="col-md-9">
              <p>
                <b>{% trans "Description" %}: </b>
                {{ service.technical_interface.description }}
              </p>
              {% if service.technical_interface.version %}
                <p>
                  <b>{% trans "Version" %}:</b>
                  {{ service.technical_interface.version }}
                </p>
              {% endif %}
            </div>
          </div>

          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
              <h3 class="panel-title">{% trans "Service" %}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">{% trans "Infrastructure Reference Documents" %} ({% trans "SWIM Reference" %})</h3>
                    </div>
                    <div class="list-group">
                      {% for each in service.technical_interface.infrastructure_reference_documents.all %}
                          <li class="list-group-item">
                            <p>
                              <img src="{{ each.image.url }}" alt="logo" width="50">
                              <a href="{% url 'registry:infrastructure_reference_document_detail' pk=each.pk %}">{{ each.name }}</a>
                            </p>
                            <p>
                              {{ each.description|truncatechars:100 }}
                            </p>
                          </li>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">{% trans "Technical Interface Documents" %} ({% trans "Implementation Specific" %})</h3>
                    </div>
                    <div class="list-group">
                      {% for each in service.technical_interface.documents.all %}
                          <li class="list-group-item">
                            <p>
                              <img src="{{ each.image.url }}" alt="logo" width="50">
                              <a href="{% url 'registry:technical_interface_document_detail' pk=each.pk %}">{{ each.name }}</a>
                            </p>
                            <p>
                              {{ each.description }}
                            </p>
                          </li>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
              <h3 class="panel-title">{% trans "Information" %}</h3>
            </div>
            <div class="panel-body">
               <div class="row">
                <div class="col-md-6">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">{% trans "Data Standards" %} ({% trans "SWIM Reference" %})</h3>
                    </div>
                    <div class="list-group">
                      {% for each in service.technical_interface.data_standards.all %}
                          <li class="list-group-item">
                            <p>
                              <img src="{{ each.image.url }}" alt="logo" width="50">
                              <a href="{% url 'registry:data_standard_detail' pk=each.pk %}">{{ each.name }}</a>
                            </p>
                            <p>
                              {{ each.description|truncatechars:100 }}
                            </p>
                          </li>
                      {% endfor %}
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">{% trans "Data Exchange Formats" %} ({% trans "Implementation Specific" %})</h3>
                    </div>
                    <div class="list-group">
                      {% for each in service.technical_interface.data_exchange_formats.all %}
                          <li class="list-group-item">
                            <p>
                              <img src="{{ each.image.url }}" alt="logo" width="50">
                              <a href="{% url 'registry:service_data_exchange_format_detail' pk=each.pk %}">{{ each.name }}</a>
                            </p>
                            <p>
                              {{ each.description|truncatechars:100 }}
                            </p>
                          </li>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading">
              <h3 class="panel-title">{% trans "Infrastructure" %}</h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">{% trans "SWIM Infrastructure Profile" %} ({% trans "SWIM Reference" %})</h3>
                    </div>
                    <div class="list-group">
                      <li class="list-group-item">
                        <p>
                          <img src="{{ service.technical_interface.infrastructure_profile.image.url }}" alt="logo" width="50">
                          <a href="{% url 'registry:infrastructure_profile_detail' pk=service.technical_interface.infrastructure_profile.pk %}">{{ service.technical_interface.infrastructure_profile.name }}</a>
                        </p>
                        <p>
                          {{ service.technical_interface.infrastructure_profile.description | truncatechars:100 }}
                        </p>
                      </li>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">{% trans "Infrastructure Description" %} ({% trans "Implementation Specific" %})</h3>
                    </div>
                    <div class="list-group">
                      {% if service.technical_interface.infrastructure_description %}
                        <li class="list-group-item">
                          <p>
                            <img src="{{ service.technical_interface.infrastructure_description.image.url }}" alt="logo" width="50">
                            <a href="{% url 'registry:infrastructure_description_detail' pk=service.technical_interface.infrastructure_description.pk %}">Infrastructure Description</a>
                          </p>
                          <p>
                            {{ service.technical_interface.infrastructure_description.description | truncatechars:100 }}
                          </p>
                        </li>
                      {% endif %}
                    </div>
                  </div>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title">{% trans "End Points" %} ({% trans "Implementation Specific" %})</h3>
                    </div>
                    <div class="list-group">
                      {% for each in service.technical_interface.end_points.all %}
                          <li class="list-group-item">
                              <img src="{{ each.image.url }}" alt="logo" width="50">
                              <a href="{% url 'registry:end_point_detail' pk=each.pk %}">{{ each.name }}</a>
                          </li>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

{% endblock %}