community/urls.py
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from . import views


app_name='community'

urlpatterns = [
    url(r'^register/$', views.RegisterAccountView.as_view(), name='register'),
    url(r'^profile/$', views.profile_edit, name='profile'),
    url(r'^subscriptions/$', views.subscriptions, name='subscriptions'),
    url(r'^organization/edit$', views.participant_edit, name='participant_edit'),
    url(r'^organizations/new$', views.participant_new, name='participant_new'),
    url(r'^organizations/$', login_required(views.ParticipantListView.as_view()), name='participant_list'),
    url(r'^organizations/(?P<pk>\d+)/detail/$', login_required(views.ParticipantDetailView.as_view()), name='participant_detail'),

    # Subscriptions
    url(r'^organizations/(?P<pk>\d+)/detail/toggle-subscription/$', views.participant_toggle_subscription, name='participant_toggle_subscription'),

]

registry/urls.py
from rest_framework import routers
from django.conf.urls import include
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required
from django.conf.urls import url
from .views import (index, service, document, end_point, data_standard, data_exchange_format,
                    infrastructure, technical_interface, technical_interface_binding, contact_point)

from .serializers.user import UserViewSet
from .serializers.participant import ParticipantViewSet
from .serializers.participant_category import ParticipantCategoryViewSet
from .serializers.service import ServiceViewSet
from .serializers.version_category import VersionCategoryViewSet
from .serializers.implementation import ImplementationStatusCategoryViewSet
from .serializers.implementation import ImplementationMaturityCategoryViewSet
from .serializers.registration_status_category import RegistrationStatusCategoryViewSet
from .serializers.data_category import DataCategoryViewSet
from .serializers.activity_category import ActivityCategoryViewSet
from .serializers.stakeholder_category import StakeholderCategoryViewSet
from .serializers.region_category import RegionCategoryViewSet
from .serializers.flight_phase_category import FlightPhaseCategoryViewSet
from .serializers.technical_interface import TechnicalInterfaceViewSet
from .serializers.technical_interface_binding import TechnicalInterfaceBindingProfileViewSet
from .serializers.infrastructure import InfrastructureProfileViewSet
from .serializers.data_standard import DataStandardViewSet
# from .serializers.data_exchange_format import DataExchangeFormatServiceViewSet
# from .serializers.end_point import EndPointViewSet


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register('users', UserViewSet)
router.register('participants', ParticipantViewSet)
router.register('participant-categories', ParticipantCategoryViewSet)
router.register('services', ServiceViewSet)
router.register('version-categories', VersionCategoryViewSet)
router.register('implementation-status-categories', ImplementationStatusCategoryViewSet)
router.register('implementation-maturity-categories', ImplementationMaturityCategoryViewSet)
router.register('registration-status-categories', RegistrationStatusCategoryViewSet)
router.register('data-categories', DataCategoryViewSet)
router.register('activity-categories', ActivityCategoryViewSet)
router.register('stakeholder-categories', StakeholderCategoryViewSet)
router.register('region-categories', RegionCategoryViewSet)
router.register('flight-phase-categories', FlightPhaseCategoryViewSet)
router.register('technical-interfaces', TechnicalInterfaceViewSet)
router.register('data-standards', DataStandardViewSet)
router.register('infrastructure-profiles', InfrastructureProfileViewSet)
router.register('profile-technical-interface-bindings', TechnicalInterfaceBindingProfileViewSet)


app_name='registry'

urlpatterns = [
    url(r'^api/', include(router.urls)),
    
    url(r'^login/$', login, {'template_name':'registry/login.html'}, name='login'),
    url(r'^logout/$', logout_then_login, {'login_url':'/login/'}, name='logout'),
    url(r'^registry/$', index.index_view, name='index'),

    # Service
    url(r'^organization/services/list/$', service.organization_service_list, name='participant_service_list'),
    # url(r'^services/$', login_required(service.ServiceListView.as_view()), name='service_list'),
    url(r'^services/$', service.service_list, name='service_list'),
    url(r'^services/new/$', service.service_new, name='service_new'),
    url(r'^services/(?P<pk>\d+)/detail/$', login_required(service.ServiceDetailView.as_view()), name='service_detail'),
    url(r'^services/(?P<pk>\d+)/edit/$', service.service_edit, name='service_edit'),

    # Technical Interface
    url(r'^services/(?P<pk>\d+)/technical-interface/new/$', technical_interface.technical_interface_new, name='technical_interface_new'),
    url(r'^services/(?P<pk>\d+)/technical-interface/edit/$', technical_interface.technical_interface_edit, name='technical_interface_edit'),
    url(r'^services/(?P<pk>\d+)/technical-interface/detail/$', login_required(technical_interface.TechnicalInterfaceDetailView.as_view()), name='technical_interface_detail'),

    # Infrastructure Description
    url(r'^infrastructure-description/(?P<pk>\d+)/detail/$', login_required(infrastructure.InfrastructureDescriptionDetailView.as_view()), name='infrastructure_description_detail'),
    url(r'^technical-interface/(?P<pk>\d+)/infrastructure-description/new/$', infrastructure.infrastructure_description_new, name='infrastructure_description_new'),
    url(r'^technical-interface/(?P<pk>\d+)/infrastructure-description/edit/$', infrastructure.infrastructure_description_edit, name='infrastructure_description_edit'),

    # Documents
    url(r'^reference-documents/$', document.reference_document_list, name='reference_document_list'),
    url(r'^service-documents/(?P<pk>\d+)/detail/$', login_required(document.ServiceDocumentDetailView.as_view()), name='service_document_detail'),
    url(r'^participant-documents/(?P<pk>\d+)/detail/$', login_required(document.ParticipantDocumentDetailView.as_view()), name='participant_document_detail'),
    url(r'^infrastructure-reference-documents/(?P<pk>\d+)/detail/$', login_required(document.InfrastructureReferenceDocumentDetailView.as_view()), name='infrastructure_reference_document_detail'),
    url(r'^infrastructure-description-documents/(?P<pk>\d+)/detail/$', login_required(document.InfrastructureDescriptionDocumentDetailView.as_view()), name='infrastructure_description_document_detail'),
    url(r'^service-data-exchange-format-documents/(?P<pk>\d+)/detail/$', login_required(document.DataExchangeFormatServiceDocumentDetailView.as_view()), name='data_exchange_format_service_document_detail'),
    url(r'^technical-interface-documents/(?P<pk>\d+)/detail/$', login_required(document.TechnicalInterfaceDocumentDetailView.as_view()), name='technical_interface_document_detail'),

    # Contact Points
    url(r'^service-contact-points/(?P<pk>\d+)/detail/$', login_required(contact_point.ServiceContactPointDetailView.as_view()), name='service_contact_point_detail'),
    url(r'^participant-contact-points/(?P<pk>\d+)/detail/$', login_required(contact_point.ParticipantContactPointDetailView.as_view()), name='participant_contact_point_detail'),

    # End Points
    url(r'^technical-interface/(?P<pk>\d+)/end-points/edit/$', end_point.end_points_edit, name='end_points_edit'),
    url(r'^end-points/(?P<pk>\d+)/detail/$', login_required(end_point.EndPointDetailView.as_view()), name='end_point_detail'),

    # Data Standards
    url(r'^data-standards/(?P<pk>\d+)/detail/$', login_required(data_standard.DataStandardDetailView.as_view()), name='data_standard_detail'),

    # Data Exchange Formats
    url(r'^technical-interface/(?P<pk>\d+)/data-exchange-formats/edit/$', data_exchange_format.data_exchange_formats_edit, name='data_exchange_formats_edit'),
    url(r'^service-data-exchange-formats/(?P<pk>\d+)/detail/$', login_required(data_exchange_format.DataExchangeFormatServiceDetailView.as_view()), name='service_data_exchange_format_detail'),

    # Infrastructure Profile
    url(r'^infrastructure-profile/(?P<pk>\d+)/detail/$', login_required(infrastructure.InfrastructureProfileDetailView.as_view()), name='infrastructure_profile_detail'),

    # Technical Interface Binding
    url(r'^infrastructure-profile/technical-interface-binding/(?P<pk>\d+)/detail/$', login_required(technical_interface_binding.TechnicalInterfaceBindingProfileDetailView.as_view()), name='profile_technical_interface_binding_detail'),
    url(r'^infrastructure-description/technical-interface-binding/(?P<pk>\d+)/detail/$', login_required(technical_interface_binding.TechnicalInterfaceBindingDescriptionDetailView.as_view()), name='description_technical_interface_binding_detail'),

    # Subscriptions
    url(r'^services/(?P<pk>\d+)/detail/toggle-subscription/$', service.service_toggle_subscription, name='service_toggle_subscription'),


    # url(r'^about/$', views.about, name='about'),
]

# ReferenceDocumentDetailView
# DataExchangeFormatApplicationDocumentDetailView
# ApplicationDocumentDetailView
# ParticipantDocumentDetailView

swim_registry/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
#from .admin import admin_site
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from .settings.base import MEDIA_ROOT, MEDIA_URL


urlpatterns = i18n_patterns(
    # url(r'^admin/', include(admin_site.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^', include('website.urls')),
    url(r'^', include('community.urls')),
    url(r'^', include('registry.urls')),
)
urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

admin.site.site_header = _('SWIM Registry Administration')

website/urls.py
from django.conf.urls import url
from . import views

app_name='website'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

website/views.py
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

def index(request):
    """View que renderiza página principal do website"""
    return render(request, 'index.html')

website/templates/index.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta content="" name="description">
    <meta content="" name="author">
    <title>{% trans 'SWIM Registry Brazil' %}</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic" rel="stylesheet" type="text/css">
    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
    <!-- Theme CSS -->
    <link href="{% static 'css/creative.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</link></link></link></link></link></link></meta></meta></meta></meta></meta></head>
<body id="page-top">
    <nav class="navbar navbar-default navbar-fixed-top" id="mainNav">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
                    <span class="sr-only">{% trans 'Toggle navigation' %}</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">{% trans 'SWIM Registry Brazil' %}</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#about">{% trans 'About' %}</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">{% trans 'Services' %}</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#organizations">{% trans 'Organizations' %}</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">{% trans 'Contact' %}</a>
                    </li>
                    <li>
                        <a href="{% url 'registry:login' %}">{% trans 'Login' %}</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 id="homeHeading">{% trans 'SWIM Registry Brazil' %}</h1>
                <hr>
                <!--<p>An initiative of TransLab in partnership with Boeing.</p>-->
                <p>{% trans 'An initiative of Translab in University of Brasília.' %}</p>
                <a class="btn btn-primary btn-xl page-scroll" href="#about">{% trans 'Find Out More' %}</a>
            </hr></div>
        </div>
    </header>
    <section class="bg-primary" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">{% trans 'About' %}</h2>
                    <hr class="light">
                    <p class="text-faded">{% trans 'System-Wide Information Management (SWIM) consists of standards, infrastructure and governance enabling the management of air traffic related information and its exchange between qualified parties via interoperable services.' %}</p>
                    <p class="text-faded">{% trans 'SWIM Registry Brazil will serve as the general repository to SWIM-related services in Brazil. Here you will find out all the information necessary to discover and access the list of services available in SWIM Brazil.' %}</p>
                    <!--<a href="#services" class="page-scroll btn btn-default btn-xl sr-button">Get Started</a>-->
                </hr></div>
            </div>
        </div>
    </section>
    <section id="services">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">{% trans 'Services' %}</h2>
                    <hr class="primary">
                </hr></div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-line-chart text-primary sr-icons"></i>
                        <h3>{% trans 'Aeronautical' %}</h3>
                        <p class="text-muted">{% trans 'Aeronautical information assembled, analyzed and formatted.' %}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-plane text-primary sr-icons"></i>
                        <h3>{% trans 'Flight trajectory' %}</h3>
                        <p class="text-muted">{% trans 'The detailed route of the aircraft defined in four dimensions 4D (with the time component included).' %}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-bolt text-primary sr-icons"></i>
                        <h3>{% trans 'Meteorological' %}</h3>
                        <p class="text-muted">{% trans "Information on the state of earth's atmosphere for air traffic control." %}</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="service-box">
                        <i class="fa fa-4x fa-users text-primary sr-icons"></i>
                        <h3>{% trans 'Other services' %}</h3>
                        <p class="text-muted">{% trans 'Aerodrome operations, Surveillance, Environment, and other aspects related to air traffic management.' %}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <aside id="organizations">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">{% trans 'Organizations' %}</h2>
                    <hr class="primary">
                    <p>{% trans 'TransLab is a Centre of Excellence for Research and Development of Computational Models applied to Air Transportation in the Department of Computer Science, University of Brasilia (UnB), Brazil. The mission of TransLab is to incorporate technology into society, especially, air transportation and informatics application.' %}</p>
                </hr></div>
            </div>
        </div>
        <div class="container">
            <div class="row logos">
                <div class="col-md-offset-4 col-md-4 col-sm-12">
                    <a href="#">
                        <img alt="" class="img-responsive" src="{% static 'img/logos/unb-gray.png' %}">
                    </img></a>
                </div>
<!--<div class="col-md-offset-2 col-md-5 col-sm-6">
                <a href="#">
                    <img src="{% static 'img/logos/unb-gray.png' %}" class="img-responsive" alt="">
                </a>
            </div>
            <div class="col-md-5 col-sm-6">
                <a href="#">
                    <img src="{% static 'img/logos/boeing-gray.png' %}" class="img-responsive img-centered" alt="">
                </a>
            </div> -->
        </div>
    </div>
</aside>
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>{% trans 'Register to have access to the available services' %}</h2>
            <a class="btn btn-default btn-xl sr-button" href="{% url 'community:register' %}">{% trans 'Register' %}</a>
        </div>
    </div>
</aside>
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">{% trans 'Contact us' %}</h2>
                <hr class="primary">
                <p>{% trans 'Suggestions? Give us a call or send us an email and we will get back to you as soon as possible.' %}</p>
            </hr></div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <i class="fa fa-phone fa-3x sr-contact"></i>
                <p>{% trans '+55 61-3107-3679' %}</p>
            </div>
            <div class="col-lg-4 text-center">
                <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                <p><a href="mailto:translab@unb.br">{% trans 'translab@unb.br' %}</a></p>
            </div>
        </div>
    </div>
</section>
<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Plugin JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
<script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
<!-- Theme JavaScript -->
<script src="{% static 'js/creative.min.js' %}"></script>
</body>
</html>